# Generated by Django 5.0.1 on 2024-02-01 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=6000)),
                ('imgPath', models.CharField(max_length=300)),
                ('duration', models.IntegerField()),
                ('genre', models.CharField(max_length=300)),
                ('language', models.CharField(max_length=30)),
                ('userRating', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='mpaaRating',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='movies.movies')),
                ('type', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'mpaaRating',
            },
        ),
    ]
